/*podlaczenie biblioteki*/
libname danepro
base
'/home/u63796376/daneProjekt';

/* w tym pliku wygenerowana są zbiory, w których dane  */
/* trzeba wpisać "z palca". Te zbiory nastepnie posluza do  */
/* automatycznego generowania danych */

/*--------wygenerowanie zbioru z nazwami krajow---------------*/

data danepro.Countries;
  countryId=.;
  length Country $ 40;
	countryId = 1; Country = 'Afghanistan'; output;
	countryID = 2; Country = 'Albania'; output;
	countryID = 3; Country = 'Algeria'; output;
	countryID = 4; Country = 'Andorra'; output;
	countryID = 5; Country = 'Angola'; output;
	countryID = 6; Country = 'Antigua and Barbuda'; output;
	countryID = 7; Country = 'Argentina'; output;
	countryID = 8; Country = 'Armenia'; output;
	countryID = 9; Country = 'Australia'; output;
	countryID = 10; Country = 'Austria'; output;
	countryID = 11; Country = 'Azerbaijan'; output;
	countryID = 12; Country = 'Bahamas'; output;
	countryID = 13; Country = 'Bahrain'; output;
	countryID = 14; Country = 'Bangladesh'; output;
	countryID = 15; Country = 'Barbados'; output;
	countryID = 16; Country = 'Belarus'; output;
	countryID = 17; Country = 'Belgium'; output;
	countryID = 18; Country = 'Belize'; output;
	countryID = 19; Country = 'Benin'; output;
	countryID = 20; Country = 'Bhutan'; output;
	countryID = 21; Country = 'Bolivia'; output;
	countryID = 22; Country = 'Bosnia and Herzegovina'; output;
	countryID = 23; Country = 'Botswana'; output;
	countryID = 24; Country = 'Brazil'; output;
	countryID = 25; Country = 'Brunei'; output;
	countryID = 26; Country = 'Bulgaria'; output;
	countryID = 27; Country = 'Burkina Faso'; output;
	countryID = 28; Country = 'Burundi'; output;
	countryID = 29; Country = 'Cabo Verde'; output;
	countryID = 30; Country = 'Cambodia'; output;
	countryID = 31; Country = 'Cameroon'; output;
	countryID = 32; Country = 'Canada'; output;
	countryID = 33; Country = 'Central African Republic'; output;
	countryID = 34; Country = 'Chad'; output;
	countryID = 35; Country = 'Chile'; output;
	countryID = 36; Country = 'China'; output;
	countryID = 37; Country = 'Colombia'; output;
	countryID = 38; Country = 'Comoros'; output;
	countryID = 39; Country = 'Congo'; output;
	countryID = 40; Country = 'Costa Rica'; output;
	countryID = 41; Country = 'Croatia'; output;
	countryID = 42; Country = 'Cuba'; output;
	countryID = 43; Country = 'Cyprus'; output;
	countryID = 44; Country = 'Czechia'; output;
	countryID = 45; Country = 'Denmark'; output;
	countryID = 46; Country = 'Djibouti'; output;
	countryID = 47; Country = 'Dominica'; output;
	countryID = 48; Country = 'Dominican Republic'; output;
	countryID = 49; Country = 'Ecuador'; output;
	countryID = 50; Country = 'Egypt'; output;
	countryID = 51; Country = 'El Salvador'; output;
	countryID = 52; Country = 'Equatorial Guinea'; output;
	countryID = 53; Country = 'Eritrea'; output;
	countryID = 54; Country = 'Estonia'; output;
	countryID = 55; Country = 'Eswatini'; output;
	countryID = 56; Country = 'Ethiopia'; output;
	countryID = 57; Country = 'Fiji'; output;
	countryID = 58; Country = 'Finland'; output;
	countryID = 59; Country = 'France'; output;
	countryID = 60; Country = 'Gabon'; output;
	countryID = 61; Country = 'Gambia'; output;
	countryID = 62; Country = 'Georgia'; output;
	countryID = 63; Country = 'Germany'; output;
	countryID = 64; Country = 'Ghana'; output;
	countryID = 65; Country = 'Greece'; output;
	countryID = 66; Country = 'Grenada'; output;
	countryID = 67; Country = 'Guatemala'; output;
	countryID = 68; Country = 'Guinea'; output;
	countryID = 69; Country = 'Guinea-Bissau'; output;
	countryID = 70; Country = 'Guyana'; output;
	countryID = 71; Country = 'Haiti'; output;
	countryID = 72; Country = 'Holy See'; output;
	countryID = 73; Country = 'Honduras'; output;
	countryID = 74; Country = 'Hungary'; output;
	countryID = 75; Country = 'Iceland'; output;
	countryID = 76; Country = 'India'; output;
	countryID = 77; Country = 'Indonesia'; output;
	countryID = 78; Country = 'Iran'; output;
	countryID = 79; Country = 'Iraq'; output;
	countryID = 80; Country = 'Ireland'; output;
	countryID = 81; Country = 'Israel'; output;
	countryID = 82; Country = 'Italy'; output;
	countryID = 83; Country = 'Jamaica'; output;
	countryID = 84; Country = 'Japan'; output;
	countryID = 85; Country = 'Jordan'; output;
	countryID = 86; Country = 'Kazakhstan'; output;
	countryID = 87; Country = 'Kenya'; output;
	countryID = 88; Country = 'Kiribati'; output;
	countryID = 89; Country ='Korea North'; output;
	countryID = 90; Country = 'Korea South'; output;
	countryID = 91; Country = 'Kuwait'; output;
	countryID = 92; Country = 'Kyrgyzstan'; output;
	countryID = 93; Country = 'Laos'; output;
	countryID = 94; Country = 'Latvia'; output;
	countryID = 95; Country = 'Lebanon'; output;
	countryID = 96; Country = 'Lesotho'; output;
	countryID = 97; Country = 'Liberia'; output;
	countryID = 98; Country = 'Libya'; output;
	countryID = 99; Country = 'Liechtenstein'; output;
	countryID = 100; Country = 'Lithuania'; output;
	countryID = 101; Country = 'Luxembourg'; output;
	countryID = 102; Country = 'Madagascar'; output;
	countryID = 103; Country = 'Malawi'; output;
	countryID = 104; Country = 'Malaysia'; output;
	countryID = 105; Country = 'Maldives'; output;
	countryID = 106; Country = 'Mali'; output;
	countryID = 107; Country = 'Malta'; output;
	countryID = 108; Country = 'Marshall Islands'; output;
	countryID = 109; Country = 'Mauritania'; output;
	countryID = 110; Country = 'Mauritius'; output;
	countryID = 111; Country = 'Mexico'; output;
	countryID = 112; Country = 'Micronesia'; output;
	countryID = 113; Country = 'Moldova'; output;
	countryID = 114; Country = 'Monaco'; output;
	countryID = 115; Country = 'Mongolia'; output;
	countryID = 116; Country = 'Montenegro'; output;
	countryID = 117; Country = 'Morocco'; output;
	countryID = 118; Country = 'Mozambique'; output;
	countryID = 119; Country = 'Myanma'; output;
	countryID = 120; Country = 'Namibia'; output;
	countryID = 121; Country = 'Nauru'; output;
	countryID = 122; Country = 'Nepal'; output;
	countryID = 123; Country = 'Netherlands'; output;
	countryID = 124; Country = 'New Zealand'; output;
	countryID = 125; Country = 'Nicaragua'; output;
	countryID = 126; Country = 'Niger'; output;
	countryID = 127; Country = 'Nigeria'; output;
	countryID = 128; Country = 'North Macedonia'; output;
	countryID = 129; Country = 'Norway'; output;
	countryID = 130; Country = 'Oman'; output;
	countryID = 131; Country = 'Pakistan'; output;
	countryID = 132; Country = 'Palau'; output;
	countryID = 133; Country = 'Palestine State'; output;
	countryID = 134; Country = 'Panama'; output;
	countryID = 135; Country = 'Papua New Guinea'; output;
	countryID = 136; Country = 'Paraguay'; output;
	countryID = 137; Country = 'Peru'; output;
	countryID = 138; Country = 'Philippines'; output;
	countryID = 139; Country = 'Poland'; output;
	countryID = 140; Country = 'Portugal'; output;
	countryID = 141; Country = 'Qatar'; output;
	countryID = 142; Country = 'Romania'; output;
 	countryID = 143; Country = 'Russia'; output;
  countryID = 144; Country = 'Rwanda'; output;
  countryID = 145; Country = 'Saint Kitts and Nevis'; output;
  countryID = 146; Country = 'Saint Lucia'; output;
  countryID = 147; Country = 'Saint Vincent and the Grenadines'; output;
  countryID = 148; Country = 'Samoa'; output;
  countryID = 149; Country = 'San Marino'; output;
  countryID = 150; Country = 'Sao Tome and Principe'; output;
  countryID = 151; Country = 'Saudi Arabia'; output;
  countryID = 152; Country = 'Senegal'; output;
  countryID = 153; Country = 'Serbia'; output;
  countryID = 154; Country = 'Seychelles'; output;
  countryID = 155; Country = 'Sierra Leone'; output;
  countryID = 156; Country = 'Singapore'; output;
  countryID = 157; Country = 'Slovakia'; output;
  countryID = 158; Country = 'Slovenia'; output;
  countryID = 159; Country = 'Solomon Islands'; output;
  countryID = 160; Country = 'Somalia'; output;
  countryID = 161; Country = 'South Africa'; output;
  countryID = 162; Country = 'South Sudan'; output;
  countryID = 163; Country = 'Spain'; output;
  countryID = 164; Country = 'Sri Lanka'; output;
  countryID = 165; Country = 'Sudan'; output;
  countryID = 166; Country = 'Suriname'; output;
  countryID = 167; Country = 'Sweden'; output;
  countryID = 168; Country = 'Switzerland'; output;
  countryID = 169; Country = 'Syria'; output;
  countryID = 170; Country = 'Tajikistan'; output;
  countryID = 171; Country = 'Tanzania'; output;
  countryID = 172; Country = 'Thailand'; output;
  countryID = 173; Country = 'Timor-Leste'; output;
  countryID = 174; Country = 'Togo'; output;
  countryID = 175; Country = 'Tonga'; output;
  countryID = 176; Country = 'Trinidad and Tobago'; output;
  countryID = 177; Country = 'Tunisia'; output;
  countryID = 178; Country = 'Turkey'; output;
  countryID = 179; Country = 'Turkmenistan'; output;
  countryID = 180; Country = 'Tuvalu'; output;
  countryID = 181; Country = 'Uganda'; output;
  countryID = 182; Country = 'Ukraine'; output;
  countryID = 183; Country = 'United Arab Emirates'; output;
  countryID = 184; Country = 'United Kingdom'; output;
  countryID = 185; Country = 'United States'; output;
  countryID = 186; Country = 'Uruguay'; output;
  countryID = 187; Country = 'Uzbekistan'; output;
  countryID = 188; Country = 'Vanuatu'; output;
  countryID = 189; Country = 'Venezuela'; output;
  countryID = 190; Country = 'Vietnam'; output;
  countryID = 191; Country = 'Yemen'; output;
  countryID = 192; Country = 'Zambia'; output;
  countryID = 193; Country = 'Zimbabwe'; output;
run;

/* wygenerowanie zbioru z informacjami o producentach samolotow */

data danepro.aircraftsProducers;
 producerId = .;
 keep producerId producer countryId;
 length producer $ 25;
 producerId = 1; producer='Boeing'; countryId = 185; output;
 producerId = 2; producer='Airbus'; countryId = 59; output;
 producerId = 3; producer='Embraer'; countryId = 24; output;
 producerId = 4; producer='Bombardier'; countryId = 32; output;
 producerId = 5; producer='Comac'; countryId = 36; output;
run;

/* wygenerowanie zbioru z informacjami o parametrach modeli samolotow */

data danepro.aircraftsModels;
    modelId = .; producerId = .;
    length AircraftModel $ 15 Category $ 6;
    
    modelId = 1; producerId = 1; AircraftModel = '747'; numberOfSeats = 500; Category = 'big'; output;
    modelId = 2; producerId = 1; AircraftModel = '737'; numberOfSeats = 180; Category = 'medium'; output;
    modelId = 3; producerId = 1; AircraftModel = '787 Dreamliner'; numberOfSeats = 240; Category = 'medium'; output;
    modelId = 4; producerId = 2; AircraftModel = 'A320'; numberOfSeats = 180; Category = 'medium'; output;
    modelId = 5; producerId = 2; AircraftModel = 'A350'; numberOfSeats = 300; Category = 'big'; output;
    modelId = 6; producerId = 2; AircraftModel = 'A380'; numberOfSeats = 550; Category = 'big'; output;
    modelId = 7; producerId = 3; AircraftModel = 'E190'; numberOfSeats = 100; Category = 'small'; output;
    modelId = 8; producerId = 3; AircraftModel = 'E175'; numberOfSeats = 85; Category = 'small'; output;
    modelId = 9; producerId = 3; AircraftModel = 'E195'; numberOfSeats = 120; Category = 'small'; output;
    modelId = 10; producerId = 4; AircraftModel = 'CRJ200'; numberOfSeats = 50; Category = 'small'; output;
    modelId = 11; producerId = 4; AircraftModel = 'Q400'; numberOfSeats = 78; Category = 'small'; output;
    modelId = 12; producerId = 4; AircraftModel = 'CSeries CS100'; numberOfSeats = 110; Category = 'small'; output;
    modelId = 13; producerId = 5; AircraftModel = 'C919'; numberOfSeats = 168; Category = 'medium'; output;
    modelId = 14; producerId = 5; AircraftModel = 'ARJ21'; numberOfSeats = 90; Category = 'small'; output;
run;


/* wygenerowanie zbioru z imionami */


data danepro.nazwiska;
i=.;
length lastname $ 50;
i=1; lastname='Smith'; output;
i=2; lastname='Johnson'; output;
i=3; lastname='Williams'; output;
i=4; lastname='Brown'; output;
i=5; lastname='Jones'; output;
i=6; lastname='Garcia'; output;
i=7; lastname='Miller'; output;
i=8; lastname='Davis'; output;
i=9; lastname='Martinez'; output;
i=10; lastname='Taylor'; output;
i=11; lastname='Anderson'; output;
i=12; lastname='Thomas'; output;
i=13; lastname='Hernandez'; output;
i=14; lastname='Moore'; output;
i=15; lastname='Martin'; output;
i=16; lastname='Jackson'; output;
i=17; lastname='Thompson'; output;
i=18; lastname='White'; output;
i=19; lastname='Lopez'; output;
i=20; lastname='Lee'; output;
i=21; lastname='Harris'; output;
i=22; lastname='Clark'; output;
i=23; lastname='Robinson'; output;
i=24; lastname='Lewis'; output;
i=25; lastname='Walker'; output;
i=26; lastname='Young'; output;
i=27; lastname='Allen'; output;
i=28; lastname='King'; output;
i=29; lastname='Wright'; output;
i=30; lastname='Scott'; output;
i=31; lastname='Torres'; output;
i=32; lastname='Nguyen'; output;
i=33; lastname='Hill'; output;
i=34; lastname='Flores'; output;
i=35; lastname='Green'; output;
i=36; lastname='Adams'; output;
i=37; lastname='Nelson'; output;
i=38; lastname='Baker'; output;
i=39; lastname='Hall'; output;
i=40; lastname='Rivera'; output;
i=41; lastname='Carter'; output;
i=42; lastname='Mitchell'; output;
i=43; lastname='Perez'; output;
i=44; lastname='Roberts'; output;
i=45; lastname='Turner'; output;
i=46; lastname='Phillips'; output;
i=47; lastname='Campbell'; output;
i=48; lastname='Parker'; output;
i=49; lastname='Evans'; output;
i=50; lastname='Edwards'; output;
i=51; lastname='Collins'; output;
i=52; lastname='Stewart'; output;
i=53; lastname='Sanchez'; output;
i=54; lastname='Morris'; output;
i=55; lastname='Rogers'; output;
i=56; lastname='Reed'; output;
i=57; lastname='Cook'; output;
i=58; lastname='Morgan'; output;
i=59; lastname='Bell'; output;
i=60; lastname='Murphy'; output;
i=61; lastname='Bailey'; output;
i=62; lastname='Rivera'; output;
i=63; lastname='Cooper'; output;
i=64; lastname='Richardson'; output;
i=65; lastname='Cox'; output;
i=66; lastname='Howard'; output;
i=67; lastname='Ward'; output;
i=68; lastname='Torres'; output;
i=69; lastname='Peterson'; output;
i=70; lastname='Gray'; output;
i=71; lastname='Ramirez'; output;
i=72; lastname='James'; output;
i=73; lastname='Watson'; output;
i=74; lastname='Brooks'; output;
i=75; lastname='Kelly'; output;
i=76; lastname='Sanders'; output;
i=77; lastname='Price'; output;
i=78; lastname='Bennett'; output;
i=79; lastname='Wood'; output;
i=80; lastname='Barnes'; output;
i=81; lastname='Ross'; output;
i=82; lastname='Henderson'; output;
i=83; lastname='Coleman'; output;
i=84; lastname='Jenkins'; output;
i=85; lastname='Perry'; output;
i=86; lastname='Powell'; output;
i=87; lastname='Long'; output;
i=88; lastname='Patterson'; output;
i=89; lastname='Hughes'; output;
i=90; lastname='Flores'; output;
i=91; lastname='Washington'; output;
i=92; lastname='Butler'; output;
i=93; lastname='Simmons'; output;
i=94; lastname='Foster'; output;
i=95; lastname='Gonzales'; output;
i=96; lastname='Bryant'; output;
i=97; lastname='Alexander'; output;
i=98; lastname='Russell'; output;
i=99; lastname='Griffin'; output;
i=100; lastname='Diaz'; output;
i=101; lastname='Hayes'; output;
i=102; lastname='Myers'; output;
i=103; lastname='Ford'; output;
i=104; lastname='Hamilton'; output;
i=105; lastname='Graham'; output;
i=106; lastname='Sullivan'; output;
i=107; lastname='Wallace'; output;
i=108; lastname='Woods'; output;
i=109; lastname='Cole'; output;
i=110; lastname='West'; output;
i=111; lastname='Jordan'; output;
i=112; lastname='Owens'; output;
i=113; lastname='Reynolds'; output;
i=114; lastname='Fisher'; output;
i=115; lastname='Ellis'; output;
i=116; lastname='Harrison'; output;
i=117; lastname='Gibson'; output;
i=118; lastname='McDonald'; output;
i=119; lastname='Cruz'; output;
i=120; lastname='Marshall'; output;
i=121; lastname='Ortiz'; output;
i=122; lastname='Gomez'; output;
i=123; lastname='Murray'; output;
i=124; lastname='Freeman'; output;
i=125; lastname='Wells'; output;
i=126; lastname='Webb'; output;
i=127; lastname='Simpson'; output;
i=128; lastname='Stevens'; output;
i=129; lastname='Tucker'; output;
i=130; lastname='Porter'; output;
i=131; lastname='Hunter'; output;
i=132; lastname='Hicks'; output;
i=133; lastname='Crawford'; output;
i=134; lastname='Henry'; output;
i=135; lastname='Boyd'; output;
i=136; lastname='Mason'; output;
i=137; lastname='Morales'; output;
i=138; lastname='Kennedy'; output;
i=139; lastname='Warren'; output;
i=140; lastname='Dixon'; output;
i=141; lastname='Ramos'; output;
i=142; lastname='Reyes'; output;
i=143; lastname='Burns'; output;
i=144; lastname='Gordon'; output;
i=145; lastname='Shaw'; output;
i=146; lastname='Holmes'; output;
i=147; lastname='Rice'; output;
i=148; lastname='Robertson'; output;
i=149; lastname='Hunt'; output;
i=150; lastname='Black'; output;
run;

/* wygenerowanie zbioru z nazwiskami */

data danepro.imiona;
i=.;
length firstname $ 50;
i=1; firstname='James'; output;
i=2; firstname='Mary'; output;
i=3; firstname='John'; output;
i=4; firstname='Patricia'; output;
i=5; firstname='Robert'; output;
i=6; firstname='Jennifer'; output;
i=7; firstname='Michael'; output;
i=8; firstname='Linda'; output;
i=9; firstname='William'; output;
i=10; firstname='Elizabeth'; output;
i=11; firstname='David'; output;
i=12; firstname='Barbara'; output;
i=13; firstname='Richard'; output;
i=14; firstname='Susan'; output;
i=15; firstname='Joseph'; output;
i=16; firstname='Jessica'; output;
i=17; firstname='Thomas'; output;
i=18; firstname='Sarah'; output;
i=19; firstname='Charles'; output;
i=20; firstname='Karen'; output;
i=21; firstname='Christopher'; output;
i=22; firstname='Nancy'; output;
i=23; firstname='Daniel'; output;
i=24; firstname='Lisa'; output;
i=25; firstname='Matthew'; output;
i=26; firstname='Margaret'; output;
i=27; firstname='Anthony'; output;
i=28; firstname='Betty'; output;
i=29; firstname='Mark'; output;
i=30; firstname='Sandra'; output;
i=31; firstname='Donald'; output;
i=32; firstname='Ashley'; output;
i=33; firstname='Steven'; output;
i=34; firstname='Dorothy'; output;
i=35; firstname='Paul'; output;
i=36; firstname='Kimberly'; output;
i=37; firstname='Andrew'; output;
i=38; firstname='Emily'; output;
i=39; firstname='Joshua'; output;
i=40; firstname='Donna'; output;
i=41; firstname='Kenneth'; output;
i=42; firstname='Michelle'; output;
i=43; firstname='Kevin'; output;
i=44; firstname='Carol'; output;
i=45; firstname='Brian'; output;
i=46; firstname='Amanda'; output;
i=47; firstname='George'; output;
i=48; firstname='Melissa'; output;
i=49; firstname='Edward'; output;
i=50; firstname='Deborah'; output;
i=51; firstname='Ronald'; output;
i=52; firstname='Stephanie'; output;
i=53; firstname='Timothy'; output;
i=54; firstname='Rebecca'; output;
i=55; firstname='Jason'; output;
i=56; firstname='Sharon'; output;
i=57; firstname='Jeffrey'; output;
i=58; firstname='Laura'; output;
i=59; firstname='Ryan'; output;
i=60; firstname='Cynthia'; output;
i=61; firstname='Jacob'; output;
i=62; firstname='Kathleen'; output;
i=63; firstname='Gary'; output;
i=64; firstname='Amy'; output;
i=65; firstname='Nicholas'; output;
i=66; firstname='Angela'; output;
i=67; firstname='Eric'; output;
i=68; firstname='Shirley'; output;
i=69; firstname='Jonathan'; output;
i=70; firstname='Emma'; output;
i=71; firstname='Stephen'; output;
i=72; firstname='Anna'; output;
i=73; firstname='Larry'; output;
i=74; firstname='Carolyn'; output;
i=75; firstname='Justin'; output;
i=76; firstname='Martha'; output;
i=77; firstname='Scott'; output;
i=78; firstname='Ruth'; output;
i=79; firstname='Brandon'; output;
i=80; firstname='Debra'; output;
i=81; firstname='Frank'; output;
i=82; firstname='Frances'; output;
i=83; firstname='Benjamin'; output;
i=84; firstname='Alice'; output;
i=85; firstname='Gregory'; output;
i=86; firstname='Jean'; output;
i=87; firstname='Raymond'; output;
i=88; firstname='Hannah'; output;
i=89; firstname='Samuel'; output;
i=90; firstname='Kathryn'; output;
i=91; firstname='Patrick'; output;
i=92; firstname='Gloria'; output;
i=93; firstname='Alexander'; output;
i=94; firstname='Teresa'; output;
i=95; firstname='Jack'; output;
i=96; firstname='Sara'; output;
i=97; firstname='Dennis'; output;
i=98; firstname='Janice'; output;
i=99; firstname='Jerry'; output;
i=100; firstname='Diane'; output;
i=101; firstname='Tyler'; output;
i=102; firstname='Julia'; output;
i=103; firstname='Aaron'; output;
i=104; firstname='Marie'; output;
i=105; firstname='Jose'; output;
i=106; firstname='Madison'; output;
i=107; firstname='Adam'; output;
i=108; firstname='Grace'; output;
i=109; firstname='Henry'; output;
i=110; firstname='Rose'; output;
i=111; firstname='Nathan'; output;
i=112; firstname='Beverly'; output;
i=113; firstname='Douglas'; output;
i=114; firstname='Denise'; output;
i=115; firstname='Zachary'; output;
i=116; firstname='Marilyn'; output;
i=117; firstname='Peter'; output;
i=118; firstname='Amber'; output;
i=119; firstname='Kyle'; output;
i=120; firstname='Danielle'; output;
i=121; firstname='Walter'; output;
i=122; firstname='Abigail'; output;
i=123; firstname='Ethan'; output;
i=124; firstname='Brittany'; output;
i=125; firstname='Jeremy'; output;
i=126; firstname='Rosemary'; output;
i=127; firstname='Harold'; output;
i=128; firstname='Diana'; output;
i=129; firstname='Carl'; output;
i=130; firstname='Natalie'; output;
i=131; firstname='Keith'; output;
i=132; firstname='Sophia'; output;
i=133; firstname='Roger'; output;
i=134; firstname='Isabella'; output;
i=135; firstname='Arthur'; output;
i=136; firstname='Charlotte'; output;
i=137; firstname='Terry'; output;
i=138; firstname='Victoria'; output;
i=139; firstname='Sean'; output;
i=140; firstname='Evelyn'; output;
i=141; firstname='Christian'; output;
i=142; firstname='Kelly'; output;
i=143; firstname='Austin'; output;
i=144; firstname='Lauren'; output;
i=145; firstname='Joe'; output;
i=146; firstname='Lillian'; output;
i=147; firstname='Albert'; output;
i=148; firstname='Joan'; output;
i=149; firstname='Jesse'; output;
i=150; firstname='Gabriella'; output;

run;


/* wygenerowanie zbioru z informacjami o zawodach pracownikow */

data danepro.occupations;
 occupationId = .;
 length occupation $ 26;
 
 occupationId = 1; occupation = 'Data Analyst'; output;
 occupationId = 2; occupation = 'Pilot'; output;
 occupationId = 3; occupation = 'Flight Attendant'; output;
 occupationId = 4; occupation = 'Air Traffic Controller'; output;
 occupationId = 5; occupation = 'Ticketing Agent'; output;
 occupationId = 6; occupation = 'Human Resources Specialist'; output;
run;



/* wygenerowanie zbioru z informacjami o lotniskach */



data danepro.airports;
 airportId=.;
 length airportCode $ 3 name $ 80 city $ 50;  
 airportId=1; airportCode='WAW'; name='Warsaw Chopin Airport'; city='Warsaw'; countryId=139; latitude=52.2500; longitude=21.0000; output;  
 airportId=2; airportCode='HBE'; name='Borg El Arab Airport'; city='Alexandria'; countryId=50; latitude=31.2000; longitude=29.2500; output;  
 airportId=3; airportCode='AMS'; name='Amsterdam Schiphol Airport'; city='Amsterdam'; countryId=123; latitude=52.3667; longitude=4.9000; output;  
 airportId=4; airportCode='ATH'; name='Athens International Airport'; city='Athens'; countryId=65; latitude=37.9667; longitude=23.7167; output;  
 airportId=5; airportCode='BKK'; name='Suvarnabhumi Airport'; city='Bangkok'; countryId=172; latitude=13.7500; longitude=100.5167; output;  
 airportId=6; airportCode='BOG'; name='El Dorado International Airport'; city='Bogota'; countryId=37; latitude=4.5833; longitude=-74.0667; output;  
 airportId=7; airportCode='BOM'; name='Chhatrapati Shivaji Maharaj International Airport'; city='Mumbai'; countryId=76; latitude=19.0000; longitude=72.8333; output;  
 airportId=8; airportCode='BSB'; name='Brasília International Airport'; city='Brasília'; countryId=24; latitude=-15.7833; longitude=-47.8667; output;  
 airportId=9; airportCode='BRU'; name='Brussels Airport'; city='Brussels'; countryId=17; latitude=50.8333; longitude=4.3333; output;  
 airportId=10; airportCode='BUD'; name='Budapest Ferenc Liszt International Airport'; city='Budapest'; countryId=74; latitude=47.5000; longitude=19.0833; output;  
 airportId=11; airportCode='EZE'; name='Ministro Pistarini International Airport'; city='Buenos Aires'; countryId=7; latitude=-34.6000; longitude=-58.3833; output;  
 airportId=12; airportCode='CCS'; name='Simón Bolívar International Airport'; city='Caracas'; countryId=186; latitude=10.4833; longitude=-66.8500; output;  
 airportId=13; airportCode='CMN'; name='Mohammed V International Airport'; city='Casablanca'; countryId=117; latitude=33.5667; longitude=-7.5833; output;  
 airportId=14; airportCode='ORD'; name='OHare International Airport'; city='Chicago'; countryId=185; latitude=41.9000; longitude=-87.6333; output;  
 airportId=15; airportCode='DKR'; name='Blaise Diagne International Airport'; city='Dakar'; countryId=152; latitude=14.6667; longitude=-17.4167; output;  
 airportId=16; airportCode='DEL'; name='Indira Gandhi International Airport'; city='Delhi'; countryId=76; latitude=28.6667; longitude=77.2167; output;  
 airportId=17; airportCode='DAC'; name='Hazrat Shahjalal International Airport'; city='Dhaka'; countryId=14; latitude=23.7000; longitude=90.3833; output;  
 airportId=18; airportCode='DXB'; name='Dubai International Airport'; city='Dubai'; countryId=183; latitude=25.2667; longitude=55.3000; output;  
 airportId=19; airportCode='CGK'; name='Soekarno-Hatta International Airport'; city='Jakarta'; countryId=77; latitude=-6.1667; longitude=106.8000; output;  
 airportId=20; airportCode='FLO'; name='Florence Airport'; city='Florence'; countryId=82; latitude=43.7667; longitude=11.2500; output;  
 airportId=21; airportCode='GVA'; name='Geneva Airport'; city='Geneva'; countryId=168; latitude=46.2667; longitude=6.1500; output;  
 airportId=22; airportCode='HAM'; name='Hamburg Airport'; city='Hamburg'; countryId=63; latitude=53.5500; longitude=9.9833; output;  
 airportId=23; airportCode='HAN'; name='Noi Bai International Airport'; city='Hanoi'; countryId=190; latitude=21.0333; longitude=105.8500; output;  
 airportId=24; airportCode='HAV'; name='José Martí International Airport'; city='Havana'; countryId=42; latitude=23.1333; longitude=-82.3833; output;  
 airportId=25; airportCode='HKG'; name='Hong Kong International Airport'; city='Hong Kong'; countryId=36; latitude=22.3167; longitude=114.0333; output;  
 airportId=26; airportCode='JRS'; name='Jerusalem Airport'; city='Jerusalem'; countryId=81; latitude=31.7833; longitude=35.2167; output;  
 airportId=27; airportCode='JNB'; name='O.R. Tambo International Airport'; city='Johannesburg'; countryId=161; latitude=-26.2000; longitude=28.0500; output;  
 airportId=28; airportCode='HND'; name='Tokyo Haneda Airport'; city='Tokyo'; countryId=84; latitude=35.7000; longitude=139.7667; output;  
 airportId=29; airportCode='CAI'; name='Cairo International Airport'; city='Cairo'; countryId=50; latitude=31.3667; longitude=30.0500; output;  
 airportId=30; airportCode='CAN'; name='Guangzhou Baiyun International Airport'; city='Guangzhou'; countryId=36; latitude=23.1667; longitude=113.2667; output;  
 airportId=31; airportCode='CPT'; name='Cape Town International Airport'; city='Cape Town'; countryId=161; latitude=-33.9333; longitude=18.4833; output;  
 airportId=32; airportCode='KHI'; name='Jinnah International Airport'; city='Karachi'; countryId=131; latitude=24.8667; longitude=67.0167; output;  
 airportId=33; airportCode='KBP'; name='Boryspil International Airport'; city='Kyiv'; countryId=182; latitude=50.4500; longitude=30.5167; output;  
 airportId=34; airportCode='KRK'; name='John Paul II International Airport'; city='Cracow'; countryId=139; latitude=50.0667; longitude=19.9333; output;  
 airportId=35; airportCode='KUL'; name='Kuala Lumpur International Airport'; city='Kuala Lumpur'; countryId=104; latitude=2.7333; longitude=101.7000; output;
 airportId=36; airportCode='LHR'; name='Heathrow Airport'; city='London'; countryId=184; latitude=51.5000; longitude=-0.1000; output;  
 airportId=37; airportCode='LIS'; name='Humberto Delgado Airport'; city='Lisbon'; countryId=140; latitude=38.7000; longitude=-9.1833; output;  
 airportId=38; airportCode='MUC'; name='Munich Airport'; city='Munich'; countryId=63; latitude=48.1333; longitude=11.5667; output;  
 airportId=39; airportCode='JFK'; name='John F. Kennedy International Airport'; city='New York'; countryId=185; latitude=40.7000; longitude=-74.0000; output;  
 airportId=40; airportCode='CDG'; name='Charles de Gaulle Airport'; city='Paris'; countryId=59; latitude=48.8667; longitude=2.3500; output;  
 airportId=41; airportCode='PEK'; name='Beijing Capital International Airport'; city='Beijing'; countryId=36; latitude=39.9000; longitude=116.3833; output;  
 airportId=42; airportCode='PRG'; name='Václav Havel Airport'; city='Prague'; countryId=44; latitude=50.0833; longitude=14.4167; output;  
 airportId=43; airportCode='ICN'; name='Incheon International Airport'; city='Seoul'; countryId=90; latitude=37.5500; longitude=126.9833; output;  
 airportId=44; airportCode='IST'; name='Istanbul Airport'; city='Istanbul'; countryId=178; latitude=41.0000; longitude=28.9667; output;  
 airportId=45; airportCode='ADD'; name='Bole International Airport'; city='Addis Ababa'; countryId=56; latitude=9.0167; longitude=38.7333; output;  
 airportId=46; airportCode='VIE'; name='Vienna International Airport'; city='Vienna'; countryId=10; latitude=48.2000; longitude=16.3667; output;  
 airportId=47; airportCode='ARN'; name='Stockholm Arlanda Airport'; city='Stockholm'; countryId=167; latitude=59.3167; longitude=18.0667; output;  
 airportId=48; airportCode='CPH'; name='Copenhagen Airport'; city='Copenhagen'; countryId=45; latitude=55.6833; longitude=12.5833; output;  
 airportId=49; airportCode='FNC'; name='Aeroporto Internacional da Madeira
 Cristiano Ronaldo'; city='Madeira'; countryId=140; latitude=32.69; longitude=-16.77; output;
 airportId=50; airportCode='KIX'; name='Kansai International Airport'; city='Kansai'; countryId=84; latitude=34.43; longitude=135.23; output;
run;

/* wygenerowanie zbioru z informacjami o typach napraw */

data danepro.repairTypes;
 typeId=.;
 length name $ 28;
 typeId=1; name = 'Engine Repair'; output;
 typeId=2; name = 'Repair of electrical systems';output;
 typeId=3; name = 'air conditioning repair';output;
 typeId=4; name = 'Chassis repair';output;
 typeId=5; name = 'Hole in the plane';output;
run;
